[package]
name = "actic_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-multipart = "0.6.1"
actix-web = {version ="4.4.0"}
dotenv = "0.15.0"
random = "0.14.0"
runtime-tokio = "0.0.0"
serde = "1.0.188"
sqlx = {version = "0.7.2", features = [
"mysql",
"macros",
"runtime-tokio",
"uuid"
]}
tokio = "1.32.0"
uuid = {version = "1.4.1", features = ["getrandom", "rand", "rng", "v4"]}



