import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { useDispatch } from "react-redux";

const initialState = {
  page: 1,
  tab: "1",
  bookList: [],
  currentBook: {}
};

export const bookSlice = createSlice({
  name: "book",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    getBooksAction: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      //   state.isAuthenticated = true;
      // console.log(">>>payload: ", action.payload);
      state.bookList = action.payload;
      // console.log(">>>check redux: ", state.book);
    },
    getCurrentBookAction: (state, action) => {
      state.currentBook = action.payload;
      console.log(">>>current book redux: ", action.payload);
    },
    changeTabAction: (state, action) => {
      console.log(">>>check redux: ", action.payload);
      state.tab = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => { },
});

export const { getBooksAction, getCurrentBookAction, changeTabAction } = bookSlice.actions;

export default bookSlice.reducer;
