import {createAsyncThunk, createSlice} from "@reduxjs/toolkit";
import {useDispatch} from "react-redux";

const initialState = {
    total: 0, books: []
};

// const isAuthenticated
export const cartSlice = createSlice({
    name: "cart", initialState, // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        initCart: (state, action) => {
            state.total = 0;
            state.books = initialState.books;
        },
        getCartAction: (state, action) => {

            state.total = action.payload.length;
            state.books = action.payload;
        },
        addBookIntoCartAction: (state, action) => {
            state.total += 1;
            console.log(">>>check total redux: ", state.total);
        }
    }, // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
    },
});

export const {getCartAction, addBookIntoCartAction, initCart} = cartSlice.actions;

export default cartSlice.reducer;
